### ISSUE TITLE
no siema

### ISSUE THREAD

**Issue by xxxzzxxx** [HakierGrzonzo/studiaNotowane#1]
Słuchaj, ja doceniam notatki, bardzo się przydają teraz na kolosach, ale we se wypierdol folder stypendium albo zprivuj bo masz pesel i numer indeksu na całego githuba otwarty. Trzymaj sie tam cieplutko

**Comment by HakierGrzonzo** [comment]
A dziękuję, BIK zastrzeżony od roku więc chwilówki nie wezmą, a jak ktoś chce za mnie do dziekanatu chodzić to bardzo przyjemnie
